apiVersion: v1
kind: Service
metadata:
  name: {{ include "scoretrak.client.fullname" . }}
  labels:
    {{- include "scoretrak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scoretrak.client.selectorLabels" . | nindent 4 }}
