{{ if .Values.config.create }}
{{ if not .Values.config.existingSecret }}
{{ $password := randAlphaNum 18 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "payments.fullname" . }}
  labels:
  {{- include "payments.labels" . | nindent 4 }}
data:
  config.yaml: |
    bankusername: {{ .Values.config.bank.username }}
    bankpassword: {{ .Values.config.bank.password }}
    bankbaseurl: {{ .Values.config.bank.url }}
    scoretrakusername: {{ .Values.config.scoretrak.username }}
    scoretrakpassword: {{ .Values.config.scoretrak.password }}
    scoretrakaddress: {{ .Values.config.scoretrak.host }}
    db:
      cockroach:
        host: {{ .Values.config.cockroachdb.db_host }}
        password: {{ .Values.config.cockroachdb.db_password | default $password }}
        clientca: {{ .Values.config.cockroachdb.clientca }}
        clientsslkey: {{ .Values.config.cockroachdb.clientsslkey }}
        clientsslcert: {{ .Values.config.cockroachdb.clientsslcert }}
        database: payments
  {{ end }}
  {{ end }}
  