apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "payments.fullname" . }}
  labels:
  {{- include "payments.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
          {{- toYaml . | nindent 14 }}
          {{- end }}
          labels:
          {{- include "payments.selectorLabels" . | nindent 14 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "payments.serviceAccountName" . }}
          securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 16 }}
          initContainers:
            - name: wait-for-scoretrak-and-bank
              image: "ghcr.io/scoretrak/utils/scoretrak-utils:v0.1.2"
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/bash"
                - "-c"
{{/*                - "for i in $(seq 1 200); do nc -z -w3 $(yq e '.scoretrakaddress' /etc/payments/config.yaml | sed 's/:/ /g') && nc -z -w3 $(yq e '.bankbaseurl' /etc/payments/config.yaml | sed -e 's/^http:\/\///g' -e 's/^https:\/\///g' | sed 's/:/ /g') && exit 0 || sleep 3; done; exit 1"*/}}
                - "base64 -D <<< Zm9yIGkgaW4gJChzZXEgMSAyMDApOyBkbyBuYyAteiAtdzMgJCh5cSBlICcuc2NvcmV0cmFrYWRkcmVzcycgL2V0Yy9wYXltZW50cy9jb25maWcueWFtbCB8IHNlZCAncy86LyAvZycpICYmIG5jIC16IC13MyAkKHlxIGUgJy5iYW5rYmFzZXVybCcgL2V0Yy9wYXltZW50cy9jb25maWcueWFtbCB8IHNlZCAtZSAncy9eaHR0cDpcL1wvLy9nJyAtZSAncy9eaHR0cHM6XC9cLy8vZycgfCBzZWQgJ3MvOi8gL2cnKSAmJiBleGl0IDAgfHwgc2xlZXAgMzsgZG9uZTsgZXhpdCAx | bash"
              volumeMounts:
                - name: config
                  mountPath: /etc/payments/
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
              {{- toYaml .Values.securityContext | nindent 18 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - ./payer
                - --config
                - /etc/payments/config.yaml
              volumeMounts:
                - name: config
                  mountPath: /etc/payments/
                - name: client-certs
                  mountPath: /cockroach-certs
              resources:
          {{- toYaml .Values.resources | nindent 18 }}
          volumes:
            - name: config
              configMap:
                name: {{ include "payments.fullname" . }}
                optional: false
            - name: client-certs
              secret:
                secretName: {{ include "global_db_client_secret_name" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
          {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 14 }}
        {{- end }}
          restartPolicy: OnFailure
