apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
  labels:
    {{- include "client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.externalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
      name: http
  selector:
    {{- include "client.selectorLabels" . | nindent 4 }}
