{{ if not .Values.envoy.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "call-nested" ( list . "envoy" "envoy.fullname" ) }}
  labels:
  {{ include "scoretrak.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }

    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: {{ .Values.envoy.service.port }} }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: routes
                virtual_hosts:
                - name: scoretrak_service
                  domains: ["{{ .Values.scoretrak.FQDN }}"]
                  routes:
                  - match:
                      prefix: "/"
                      headers:
                      - name: "Content-Type"
                        prefixMatch: "application/grpc-web-text"
                    route:
                      cluster: scoretrak-server
                      timeout: 0s
                      max_stream_duration:
                        grpc_timeout_header_max: 0s
                  - match:
                      prefix: "/"
                    route:
                      cluster: scoretrak-client
                  cors:
                    allow_origin_string_match:
                      - prefix: "*"
                    allow_methods: GET, PUT, DELETE, POST, OPTIONS
                    allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization
                    max_age: "1728000"
                    expose_headers: custom-header-1,grpc-status,grpc-message
{{ if .Values.bank.enabled }}
                - name: bank_service
                  domains: ["{{ .Values.bank.FQDN }}"]
                  routes:
                  - match:
                      prefix: "/admin"
                    route:
                      cluster: commerce_backend
                  - match:
                      prefix: "/api"
                    route:
                      cluster: commerce_backend
                  - match:
                      prefix: "/static"
                    route:
                      cluster: commerce_backend
                  - match:
                      prefix: "/"
                    route:
                      cluster: commerce_ui
{{ end }}
              http_filters:
                - name: envoy.filters.http.grpc_web
                - name: envoy.filters.http.cors
                - name: envoy.filters.http.router
      clusters:
        - name: scoretrak-server
          connect_timeout: 0.25s
          type: logical_dns
          http2_protocol_options: {}
          lb_policy: round_robin
          load_assignment:
            cluster_name: scoretrak-server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ include "call-nested" ( list . "server" "server.fullname" ) }}
                          port_value: {{ .Values.server.service.port }}

        - name: scoretrak-client
          connect_timeout: 0.25s
          type: logical_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: scoretrak-client
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ include "call-nested" ( list . "client" "client.fullname" ) }}
                          port_value: {{ .Values.client.service.port }}
{{ if .Values.bank.enabled }}
        - name: commerce_ui
          connect_timeout: 0.25s
          type: logical_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: commerce_ui
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ include "call-nested" ( list . "commerce_ui" "commerce_ui.fullname" ) }}
                          port_value: {{ .Values.commerce_ui.service.port }}
        - name: commerce_backend
          connect_timeout: 0.25s
          type: logical_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: commerce_backend
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ include "call-nested" ( list . "commerce_backend" "commerce_backend.fullname" ) }}
                          port_value: {{ .Values.commerce_backend.service.port }}
{{ end }}
{{ end }}