  {{ $password := randAlphaNum 18 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "call-nested" ( list . "bank" "bank.fullname" ) }}
  labels:
  {{- include "scoretrak.labels" . | nindent 4 }}
data:
  config.yaml: |
    bankusername: {{ .Values.config.bank.username }}
    bankpassword: {{ .Values.config.bank.password }}
    bankbaseurl: {{ .Values.config.bank.url }}
    scoretrakusername: {{ .Values.config.scoretrak.username }}
    scoretrakpassword: {{ .Values.config.scoretrak.password }}
    scoretrakaddress: {{ .Values.config.scoretrak.host }}
    db:
      cockroach:
        host: {{ .Values.config.cockroachdb.db_host }}
        password: {{ .Values.config.cockroachdb.db_password | default $password }}
        clientca: "/cockroach-certs/ca.crt"
        clientsslkey: "/cockroach-certs/tls.key"
        clientsslcert: "/cockroach-certs/tls.crt"
        database: payments