{{ if not .Values.server.config.create }}
{{ $jwtSecret := randAlphaNum 24 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "call-nested" ( list . "server" "server.fullname" ) . }}
  labels:
  {{- include "call-nested" ( list . "server" "server.labels" ) . | nindent 4 }}
data:
  config.yaml: |-
    {{ if .Values.server.config.nsq.use }}
    queue:
      use: nsq
      nsq:
        {{ $nsqdFullName := include "call-nested" ( list . "nsq" "nsq.nsqd.fullname" ) }}
        producernsqd: "{{ $nsqdFullName }}:4150"
        {{ $lookupdFullName := include "call-nested" ( list . "nsq" "nsq.nsqlookupd.fullname" ) }}
        {{ range $i, $e := until (atoi (printf "%d" (int64 .Values.nsq.nsqlookupd.replicaCount))) -}}
          - --lookupd-tcp-address={{ $lookupdFullName }}-{{ $i }}.{{ $lookupdFullName }}:4160
        {{ end -}}
    {{ else }}
    queue:
      use: none
    {{ end }}

    port: {{ .Values.server.service.grpc.port }}
    production: {{ .Values.server.config.production }}

    db:
      cockroach:
        host: {{ include "call-nested" ( list . "cockroachdb" "cockroachdb.fullname" ) }}-public
        port: {{ .Values.server.config.db.cockroach.port }}
        database: {{ .Values.server.config.db.cockroach.database }}
    {{ if .Values.cockroachdb.tls.enabled }}
        clientca: {{ .Values.server.config.db.cockroach.tls.clientca }}
        clientsslkey: {{ .Values.server.config.db.cockroach.tls.clientsslkey }}
        clientsslcert: {{ .Values.server.config.db.cockroach.tls.clientsslcert }}
    {{ else }}
        password: {{ .Values.server.config.db.cockroach.password }}
    {{ end }}

    platform:
      use: kubernetes

    jwt:
      secret: {{ $jwtSecret }}
  {{ end }}