# Default values for nsq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

adminEnabled: true
replicaCount: 1

image:
  repository: nsqio/nsq
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

resources: {}

# NSQD HELM CHART VALUES

nsqd:
  replicaCount: 3
  nsqlookupd:
    replicaCount: 3
