

service:
  port:

# COCKROACHDB HELM CHART VALUES

cockroachdb:
  # -- Specifies whether to create a cockroachdb instance
  create: true
  statefulset:
    replicas: 3
    resources:
      limits:
        memory: "2Gi"
      requests:
        memory: "2Gi"
  storage:
    persistentVolume:
      enabled: false
      size: "5Gi"
  conf:
    cache: "500Mi"
    max-sql-memory: "500Mi"
    max-offset: 1000ms
  tls:
    enabled: true

# NSQ HELM CHART VALUES

nsq:
  use: true
  nsqd:
    persistence:
      enabled: false
