{{ if not .Values.django_superuser.existingSecret }}
{{ $password := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commerce-backend.fullname" . }}-django
  labels:
  {{- include "commerce-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SUPERUSER_USERNAME: {{ .Values.config.django_superuser.username }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.config.django_superuser.password | default $password }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.config.django_superuser.email }}
{{ end }}