apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqlookupd.fullname" . }}
  labels:
    {{- include "nsqlookupd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcp.externalPort }}
      targetPort: {{ .Values.service.tcp.internalPort }}
      name: tcp
    - port: {{ .Values.service.http.externalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
      name: http
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "nsqlookupd.selectorLabels" . | nindent 4 }}
