apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsqlookupd.fullname" . }}
  labels:
    {{ include "nsqlookupd.labels" . | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy | quote }}
  {{ if .Values.global }}
  replicas: {{ .Values.global.nsqlookupd.replicaCount }}
  {{ else }}
  replicas: {{ .Values.replicaCount | int64 }}
  {{ end }}
  selector:
    matchLabels:
      {{ include "nsqlookupd.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "nsqlookupd.fullname" . }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{ include "nsqlookupd.selectorLabels" . | nindent 8 }}
      {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- if or .Values.nodeAffinity .Values.podAffinity .Values.podAntiAffinity }}
      affinity:
      {{- with .Values.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
        {{- if .Values.podAntiAffinity.type }}
        {{- if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
              labelSelector:
                matchLabels:
                  {{ include "nsqlookupd.selectorLabels" . | nindent 18 }}
        {{- else if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.podAntiAffinity.weight | int64 }}
              podAffinityTerm:
                topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
                labelSelector:
                  matchLabels:
                  {{ include "nsqlookupd.selectorLabels" . | nindent 18 }}
        {{- end }}
        {{- else }}
          {{- toYaml .Values.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /nsqlookupd
        args:
        - -tcp-address
        - "0.0.0.0:{{ .Values.service.tcp.internalPort }}"
        - -http-address
        - "0.0.0.0:{{ .Values.service.http.internalPort }}"
        ports:
        - name: tcp
          containerPort: {{ .Values.service.tcp.internalPort }}
        - name: http
          containerPort: {{ .Values.service.http.internalPort }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}