# Default values for nsqlookupd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nsqio/nsq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityConext: {}

service:
  type: ClusterIP

resources: {}

budget:
  enabled: true
  minAvailable: 1

podManagementPolicy: "OrderedReady"
updateStrategy:
  type: "RollingUpdate"

nodeAffinity: {}
podAffinity: {}
podAntiAffinity:
  type: "hard"
  topologyKey: "kubernetes.io/hostname"

topologySpreadConstraints:
  maxSkew: 1
  topologyKey: "kubernetes.io/hostname"
  whenUnsatisfiable: "DoNotSchedule"
