{{ if .Values.config.create }}
{{ $jwtSecret := randAlphaNum 24 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ if .Values.config.nsq.use }}
    queue:
      use: nsq
      nsq:
        producernsqd: {{ .Values.config.nsq.producernsqd }}
      
        nsqlookupd:
        {{ range .Values.config.nsq.nsqlookupd.nodes }}
          - {{ . }}
        {{ end }}
    {{ else }}
    queue:
      use: none
    {{ end }}

    port: {{ .Values.service.grpc.port }}
    production: {{ .Values.config.production }}
    
    db:
      cockroach:
        host: {{ .Values.config.db.cockroachdb.host }}
        port: {{ .Values.config.db.cockroachdb.port }}
        database: {{ .Values.config.db.cockroachdb.database }}
        {{ if .Values.config.db.cockroachdb.tls.enabled }}
        clientca: {{ .Values.config.db.cockroachdb.tls.clientca }}
        clientsslkey: {{ .Values.config.db.cockroachdb.tls.clientsslkey }}
        clientsslcert: {{ .Values.config.db.cockroachdb.tls.clientsslcert }}
        {{ else }}
        password: {{ .Values.config.db.cockroachdb.password }}
        {{ end }}
    
    platform:
      use: kubernetes

    jwt:
      secret: {{ $jwtSecret }}
  {{ end }}