{{ $jwtSecret := randAlphaNum 24 }}
{{ $nsqlookupdHttpPort := .Values.nsqd.nsqlookupd.service.http.externalPort }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ if .Values.nsqd.use }}
    queue:
      use: nsq
      nsq:
        {{ $nsqdFullname := include "call-nested" ( list . "nsqd" "nsqd.fullname" ) }}
        producernsqd: "{{ $nsqdFullname }}-0:{{ .Values.nsqd.service.tcp.externalPort }}"
        nsqlookupd:
        {{ $nsqlookupdFullname := include "call-nested" ( list . "nsqd.nsqlookupd" "nsqlookupd.fullname" ) }}
        {{ if .Values.global }}
        {{ range $i := until ( .Values.global.nsqlookupd.replicaCount | int ) }}
        - "{{ $nsqlookupdFullname }}-{{ $i }}.{{ $nsqlookupdFullname }}:{{ $nsqlookupdHttpPort }}"
        {{ end }}
        {{ else }}
        {{ range $i := until ( .Values.nsqd.nsqlookupd.replicaCount | int ) }}
        - "{{ $nsqlookupdFullname }}-{{ $i }}.{{ $nsqlookupdFullname }}:{{ $nsqlookupdHttpPort }}"
        {{ end }}
        {{ end }}
    {{ else }}
    queue:
      use: none
    {{ end }}

    port: {{ .Values.service.port }}
    production: {{ .Values.production }}
    
    db:
      cockroach:
        host: {{ include "call-nested" ( list . "cockroachdb" "cockroachdb.fullname" ) }}-public
        database: defaultdb
        clientca: "/cockroach-certs/ca.crt"
        clientsslkey: "/cockroach-certs/client.root.key"
        clientsslcert: "/cockroach-certs/client.root.crt"
    
    platform:
      use: kubernetes

    jwt:
      secret: {{ $jwtSecret }}