{{ if not .Values.config.existingConfig }}
{{ $jwtSecret := randAlphaNum 24 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ if .Values.config.nsq.use }}
    queue:
      use: nsq
      nsq:
        {{ range .Values.config.nsq.nsqlookupd.nodes }}
          - --lookupd-tcp-address={{ . }}
        {{ end }}
    {{ else }}
    queue:
      use: none
    {{ end }}

    port: {{ .Values.service.grpc.port }}
    production: {{ .Values.config.production }}
    
    db:
      cockroach:
{{/*        host: {{ include "call-nested" ( list . "cockroachdb" "cockroachdb.fullname" ) }}-public*/}}
        host: {{ .Values.config.db.cockroach.host }}
        port: {{ .Values.config.db.cockroach.port }}
        database: {{ .Values.config.db.cockroach.database }}
        {{ if .Values.cockroachdb.tls.enabled }}
        clientca: {{ .Values.config.db.cockroach.tls.clientca }}
        clientsslkey: {{ .Values.config.db.cockroach.tls.clientsslkey }}
        clientsslcert: {{ .Values.config.db.cockroach.tls.clientsslcert }}
        {{ else }}
        password: {{ .Values.config.db.cockroach.password }}
        {{ end }}
    
    platform:
      use: kubernetes

    jwt:
      secret: {{ $jwtSecret }}
{{ end }}
