apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - ./master
          - -config
          - /scoretrak/config.yaml
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: scoretrak-config
              mountPath: /scoretrak
            {{ if .Values.config.db.cockroachdb.tls.enabled }}
            - name: cockroachdb-client-secret
              mountPath: /cockroach-certs
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: scoretrak-config
          configMap:
            name: {{ include "server.fullname" . }}
        {{ if .Values.config.db.cockroachdb.tls.enabled }}
        - name: cockroachdb-client-secret
          secret:
            secretName: {{ include "global_db_client_secret_name" . }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
