apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
