apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-client-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-cockroachdb
type: kubernetes.io/service-account-token