apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.externalPort }}
      targetPort: {{ .Values.service.grpc.port }}
      name: grpc
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
