apiVersion: v2
name: nsqadmin
description: A Helm chart for nsq messaing platform
type: application
version: 0.2.3
appVersion: "v1.1.0"
dependencies:
- name: nsqd
  version: "0.2.3"
  repository: "https://scoretrak.github.io/helm-charts"