{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nsqadmin.name" . }}
  labels:
    {{- include "nsqadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nsqadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nsqadmin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "nsqadmin.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /nsqadmin
          args:
          {{ if .Values.global }}
          {{ range $i := until ( .Values.global.nsqlookupd.replicaCount | int ) }}
          - -lookupd-http-address
          - nsqlookupd-{{ $i }}.nsqlookupd:4161
          {{ end }}
          {{ else }}
          {{ range $i := until ( .Values.nsqlookupd.replicaCount | int ) }}
          - -lookupd-http-address
          - nsqlookupd-{{ $i }}.nsqlookupd:4161
          {{ end }}
          {{ end }}
          ports:
            - name: tcp
              containerPort: 4170
            - name: http
              containerPort: 4171
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 60
{{ end }}