apiVersion: v2
name: scoretrak
description: A Helm chart for Scoretrak

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
  - name: envoy
    version: "0.2.14"
    repository: "https://scoretrak.github.io/helm-charts"
  - name: server
    version: "0.2.14"
    repository: "https://scoretrak.github.io/helm-charts"
  - name: client
    version: "0.2.4"
    repository: "https://scoretrak.github.io/helm-charts"
  - name: cockroachdb
    version: "6.0.9"
    repository: "https://charts.cockroachdb.com/"
  - name: nsq
    version: "1.2.0"
    repository: "https://beeinventor.github.io/charts"
    condition: nsq.use