# Default values for scoretrak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


scoretrak:
  FQDN: "*"


config:
  db_names:
    - scoretrak

# ENVOY SUB HELM CHART VALUES

envoy:
  config:
    create: false


# SERVER SUB HELM CHART VALUES

server:
  config:
    create: false
    nsq:
      use: true
    db:
      cockroachdb:
        database: scoretrak
        password: ""
        tls:
          enabled: true

# BANK SUB HELM CHART VALUES

bank:
  enabled: false
  FQDN: "*"
    
# COMMERCE BACKEND SUB SUB HELM CHART VALUES
commercebackend:
  use: false
  config:
    create: false

# COMMERCE UI SUB SUB HELM CHART VALUES
commerceui:
  use: false
  config:
    create: false
    
payments:
  use: false
  config:
    create: false

    
# COCKROACHDB SUB HELM CHART VALUES

cockroachdb:
  storage:
    persistentVolume:
      size: "10Gi"
  tls:
    enabled: true
    
  init:
    provisioning:
      enabled: true
      databases:
        - name: scoretrak
        - name: bank
        - name: payments

# NSQ SUB HELM CHART VALUES
nsq:
  use: true
  nsqd:
    persistence:
      enabled: false
