# Default values for scoretrak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


scoretrak:
  FQDN: "*"
  bank:
    enabled: false
    FQDN: bank.example.com


config:
  db_names:
    - scoretrak

# ENVOY SUB HELM CHART VALUES

envoy:
  config:
    create: false


# SERVER SUB HELM CHART VALUES

server:
  config:
    admin:
      username: "admin"
    create: false
    nsq:
      use: true
    db:
      cockroachdb:
        database: scoretrak
        password: ""
        tls:
          enabled: true

# BANK SUB HELM CHART VALUES

bank:
  admin:
    username: bank
# COMMERCE BACKEND SUB SUB HELM CHART VALUES
  commerce-backend:
 
# COMMERCE UI SUB SUB HELM CHART VALUES
  commerce-ui: 
    
payments:
  admin:
    username: payments
 

# COCKROACHDB SUB HELM CHART VALUES

cockroachdb:
  statefulset:
    replicas: 3
    resources:
      limits:
        memory: "2Gi"
      requests:
        memory: "2Gi"
  storage:
    persistentVolume:
      enabled: false
      size: "5Gi"
  conf:
    cache: "500Mi"
    max-sql-memory: "500Mi"
    max-offset: 1000ms
  tls:
    enabled: true
    
  init:
    provisioning:
      enabled: true
      databases:
        - name: scoretrak
        - name: bank
        - name: payments

# NSQ SUB HELM CHART VALUES
nsq:
  use: true
  nsqd:
    persistence:
      enabled: false
