# Default values for scoretrak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#sub chart values




# NSQ HELM CHART VALUES

nsq:
  use: true
  nsqd:
    persistence:
      enabled: false