{{ if .Values.config.create }}
{{ $password := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commercebackend.fullname" . }}-django
  labels:
  {{- include "commercebackend.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SUPERUSER_USERNAME: {{ .Values.config.admin.username | b64enc }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.config.admin.password | default $password | b64enc }}
{{ end }}
