apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsqd.name" . }}
  labels:
    {{ include "nsqd.labels" . | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy | quote }}
  replicas: {{ .Values.replicaCount | int64 }}
  selector:
    matchLabels:
      {{ include "nsqd.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "nsqd.name" . }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{ include "nsqd.selectorLabels" . | nindent 8 }}
      {{ with .Values.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- if or .Values.nodeAffinity .Values.podAffinity .Values.podAntiAffinity }}
      affinity:
      {{- with .Values.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
        {{- if .Values.podAntiAffinity.type }}
        {{- if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
              labelSelector:
                matchLabels:
                  {{ include "nsqd.selectorLabels" . | nindent 18 }}
                  {{- with .Values.labels }}
                    {{- toYaml . | nindent 18 }}
                  {{- end }}
        {{- else if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.podAntiAffinity.weight | int64 }}
              podAffinityTerm:
                topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
                labelSelector:
                  matchLabels:
                  {{ include "nsqd.selectorLabels" . | nindent 18 }}
                  {{- with .Values.labels }}
                    {{- toYaml . | nindent 18 }}
                  {{- end }}
        {{- end }}
        {{- else }}
          {{- toYaml .Values.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version }}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            {{ include  "nsqd.selectorLabels" . | nindent 12 }}
          {{- with .Values.labels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.topologySpreadConstraints }}
        maxSkew: {{ .maxSkew }}
        topologyKey: {{ .topologyKey }}
        whenUnsatisfiable: {{ .whenUnsatisfiable }}
      {{- end }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ include "nsqd.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /nsqd
        args:
        - -data-path
        - /data
        {{ if .Values.global }}
        {{ range $i := until ( .Values.global.nsqlookupd.replicaCount | int ) }}
        - -lookupd-tcp-address
        - nsqlookupd-{{ $i }}.nsqlookupd:4160
        {{ end }}
        {{ else }}
        {{ range $i := until ( .Values.nsqlookupd.replicaCount | int ) }}
        - -lookupd-tcp-address
        - nsqlookupd-{{ $i }}.nsqlookupd:4160
        {{ end }}
        {{ end }}
        - -broadcast-address
        - $(HOSTNAME).{{ include "nsqd.name" . }}
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: tcp
          containerPort: 4150
        - name: http
          containerPort: 4151
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        volumeMounts:
        - name: datadir
          mountPath: /data
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: datadir
      {{ if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: datadir
      {{ else }}
        emptyDir: {}
      {{ end }}
  {{ if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
      labels:
        {{ include "nsqd.selectorLabels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{ if .Values.persistentVolume.storageClass }}
      {{ if (eq "-" .Values.persistentVolume.storageClass) }}
      storageClassName: ""
      {{ else }}
      storageClassName: {{ .Values.persistentVolume.storageClass | quote }}
      {{ end }}
      {{ end }}
      resources:
        requests:
          storage: {{ .Values.persistentVolume.size | quote }}
  {{ end }}