apiVersion: v2
name: nsqd
description: A Helm chart for nsqd, the daemon that receives, queues, and delivers messages to clients.
type: application
version: 0.2.1
appVersion: "v1.1.0"
keywords:
- nsq
- nsqd
dependencies:
- name: nsqlookupd
  version: "0.2.1"
  repository: "https://scoretrak.github.io/helm-charts"
  condition: nsqlookupd.use