# Default values for nsqd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Statefulset replica count
replicaCount: 3

image:
  # -- Container image name
  repository: nsqio/nsq
  # -- Container pull policy
  pullPolicy: IfNotPresent
  # -- Container image tag
  tag: "v1.1.0"

# -- Secrets to pull container image
imagePullSecrets: []
# -- String to override nsqlookupd.name template
nameOverride: ""
# -- String to override nsqlookupd.fullname template
fullnameOverride: ""

# -- Additional annotations for StatefulSet Pods
podAnnotations: {}

service:
  # -- Service type for nsqlookupd service
  type: ClusterIP
  tcp:
    # -- Internal tcp port to expose in StatefulSet Pods
    internalPort: 4150
    # -- External tcp port to expose for Service
    externalPort: 4150
  http:
    # -- Internal http port to expose in StatefulSet Pods
    internalPort: 4151
    # -- External http port to expose for Service
    externalPort: 4151

# -- Resource requests and limits for StatefulSet Pods
resources: {}

budget:
  # -- Enable Pod Distribution Budget for StatefulSet Pods
  enabled: true
  # -- Number of pods to be available at all times
  minAvailable: 1

# -- Pod Management Policy for StatefulSet Pod's creation and deletion order. Either "OrderedReady" or "Parallel
podManagementPolicy: "Parallel"
updateStrategy:
  # -- Update strategy for StatefulSet Pods.
  type: "RollingUpdate"

# -- Node affinity rules for StatefulSet Pods
nodeAffinity: {}
# -- Pod affinity rules for StatefulSet Pods
podAffinity: {}
# -- Pod anti-affinity rules for StatefulSet Pods
podAntiAffinity:
  # -- TYpe of auto anti-affinity rules
  type: "hard"
  topologyKey: "kubernetes.io/hostname"

persistentVolume:
  # -- Enable Persistent Volumes for StatefulSet Pods
  enabled: true
  # -- Size of Persistent Volumes for StatefulSet Pods
  size: 1Gi
  # -- Storage Class to use when creating Persistent Volumes. "-" means empty.
  # storageClass: "-"


# NSQLOOKUPD HELM CHART VALUES
# Please refer to the nsqlookupd helm chart docs for more values

# -- nsqlookupd helm chart values
nsqlookupd:
  # -- Use nsqlookupd helm chart to create nsqlookupd instances
  use: true
  # -- nsqlookupd replica count
  replicaCount: 3