{{ $nsqlookupdName := include "nsqlookupd.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nsqadmin.name" . }}
  labels:
    {{ include "nsq.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "nsq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nsq.selectorLabels" . | nindent 8 }}
        {{ include "nsqadmin.labels" . | nindent 8 }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - name: {{ include "nsqadmin.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 4170
            - name: http
              containerPort: 4171
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          command:
          - /nsqadmin
          {{ range $i := until ( default 3 .Values.nsqlookupdReplicaCount | int ) }}
          - -lookupd-http-address
          - {{ $nsqlookupdName }}-{{ $i }}.{{ $nsqlookupdName }}:4161
          {{ end }}
      terminationGracePeriodSeconds: 5