apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.name" . }}
  labels:
    {{- include "nsq.labels" . | nindent 4 }}
    {{- include "nsq.appLabel" . | nindent 4 }}
spec:
  ports:
    - port: 4150
      targetPort: 4150
      name: tcp
    - port: 4151
      targetPort: 4151
      name: http
  clusterIP: None
  selector:
    {{- include "nsqd.labels" . | nindent 4 }}
