apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqadmin.name" . }}
  labels:
    {{ include "nsq.labels" . | nindent 4 }}
    {{ include "nsq.appLabel" . | nindent 4 }}
spec:
  ports:
    - port: 4170
      targetPort: 4170
      name: tcp
    - port: 4171
      targetPort: 4171
      name: http
  selector:
    {{ include "nsqadmin.labels" . | nindent 4 }}
