apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scoretrak.envoy.fullname" . }}
  labels:
    {{- include "scoretrak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      {{- include "scoretrak.envoy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.envoy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scoretrak.envoy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.envoy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.envoy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.envoy.securityContext | nindent 12 }}
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          command:
            - envoy
          args:
            - -c
            - /config/envoy.yaml
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "scoretrak.envoy.fullname" . }}
            optional: false
      {{- with .Values.envoy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.envoy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.envoy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
