apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scoretrak.server.fullname" . }}
  labels:
    {{- include "scoretrak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "scoretrak.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scoretrak.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scoretrak.server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - master
            - --config
            - /scoretrak/config.yaml
          ports:
            - name: grpc
              containerPort: 9090
          volumeMounts:
            - name: scoretrak-config
              mountPath: /scoretrak
            {{ if .Values.server.config.db.cockroachdb.tls.enabled }}
            - name: cockroachdb-client-secret
              mountPath: /cockroach-certs
            {{ end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: scoretrak-config
          configMap:
            name: {{ include "scoretrak.server.fullname" . }}
        {{ if .Values.server.config.db.cockroachdb.tls.enabled }}
        - name: cockroachdb-client-secret
          secret:
            secretName: {{ include "global_db_client_secret_name" . }}
        {{ end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
