{{ if .Values.config.create }}
{{ if not .Values.config.admin.existingSecret }}
{{ $password := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commerce_backend.fullname" . }}-django
  labels:
  {{- include "commerce_backend.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SUPERUSER_USERNAME: {{ .Values.config.admin.username }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.config.admin.password | default $password }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.config.admin.email }}
{{ end }}
{{ end }}
