apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
  {{- include "envoy.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    {{- tpl .Values.config.value . | nindent 4 }}
