apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9901
      targetPort: 9901
      protocol: TCP
      name: admin
  selector:
    {{- include "envoy.selectorLabels" . | nindent 4 }}
